apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  ports:
  - port: 6379
  selector:
    redis-master: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
        redis-master: "true"
    spec:
      hostname: redis-master
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        # Build your own image with Dockerfile at
        #     https://github.com/Statemood/dockerfiles/tree/master/Dockerfiles/redis/4.0.12
        image: statemood/redis:4.0.12
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_MODE
          value: "master"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redisAuthPass
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 20
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-redis-master