kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-master
  annotations:
    volume.beta.kubernetes.io/storage-class: ssd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-slave-0
  annotations:
    volume.beta.kubernetes.io/storage-class: ssd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-slave-1
  annotations:
    volume.beta.kubernetes.io/storage-class: ssd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi