ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
GRANT ALL ON *.* TO root@'%'  IDENTIFIED BY 'MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;

GRANT SELECT ON mysql.db TO health_check@'%' IDENTIFIED BY 'MYSQL_HC_PASSWORD';