apiVersion: v1
kind: Service

metadata:
  name: mysql-test
  namespace: default

spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32336
  selector:
    app: mysql-test