kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-jira-software
  annotations:
    volume.beta.kubernetes.io/storage-class: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi