apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  serviceName: kafka-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:

      terminationGracePeriodSeconds: 180
      initContainers:
      - name: init-data-dir
        image: busybox
        command:
        - sh
        - -c
        - rm -rf /data/lost+found
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: k8skafka
        imagePullPolicy: Always
        image: statemood/kafka:2.1.0
        command:
        - sh
        - -c
        - "/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties --override broker.id=${HOSTNAME##*-}"
        resources:
          requests:
            memory: "1Gi"
            cpu: 500m
        ports:
        - containerPort: 9093
          name: server
        env:
        - name: KAFKA_HEAP_OPTS
          value : "-Xmx512M -Xms512M"
        - name: KAFKA_OPTS
          value: "-Dlogging.level=INFO"
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka
        - name: config
          mountPath: /opt/kafka/config/server.properties
          subPath: server.properties
        readinessProbe:
          exec:
           command:
            - sh
            - -c
            - "/opt/kafka/bin/kafka-topics.sh --list --zookeeper zk-0.zk-svc:2181,zk-1.zk-svc:2181,zk-2.zk-svc:2181"
      securityContext:
        runAsUser: 205
        fsGroup: 205
      volumes:
      - name: config
        configMap:
          defaultMode: 0644
          name: kafka
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi