apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
  namespace: redis
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: redis-init
        image: statemood/redis:4.0.11
        imagePullPolicy: Always
        command: 
        - 
        env:
        - name:  "APP_ENV"
          value: "APP_ENV_V"
        - name:  "APP_NAME"
          value: "APP_NAME_V"
        - name:  "APP_ROOT"
          value: "APP_ROOT_V"
        - name:  "APP_SERVICE"
          value: "APP_SERVICE_V"
        - name:  "APP_JOB_TYPE"
          value: "APP_JOB_TYPE_V"
        - name:  "JOB_COMMAND"
          value: "JOB_COMMAND_V"
        - name:  "APP_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: LIMIT_MAX_CPU
            memory: LIMIT_MAX_MEM
          requests:
            cpu: LIMIT_MIN_CPU
            memory: LIMIT_MIN_MEM
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: IMAGE_PULL_SECRET