kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-1
  namespace: redis
  annotations:
    volume.beta.kubernetes.io/storage-class: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi