---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
data:
  auth.password: mypassword 
  mode: cluster

---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
spec:
  template:
    spec:
      containers:
      - name: init
        image: statemood/redis:5.0.7
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        - /init-cluster.sh
        env:
        # Keep the same with statefulset.
        - name:  REDIS_NAME
          value: "redis" 
        - name: SUB_DOMAIN
          value: "redis-svc"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name:  REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: redis-cm
              key: auth.password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: zk-svc
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: client
  - port: 16379
    name: bus
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis

spec:
  serviceName: redis-svc
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: statemood/redis:5.0.7
        imagePullPolicy: Always
        env:
        - name: MYIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name:  "REDIS_MODE"
          valueFrom:
            configMapKeyRef:
              name: redis-cm
              key: mode
        - name:  "REDIS_PASSWORD"
          valueFrom:
            configMapKeyRef:
              name: redis-cm
              key: auth.password
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 150m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: data
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi