apiVersion: apps/v1beta2
kind: StatefulSet

metadata:
  name: redis
  namespace: redis

spec:
  serviceName: redis
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
      - name: redis
        image: statemood/redis:4.0.6
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "200m"
            memory: "1G"
          requests:
            cpu: "200m"
            memory: "1G"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi