{
 "title": "App Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info,namespace)"
   },
   {
    "name": "created_by_kind",
    "label": "Kind",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"},created_by_kind)"
   },
   {
    "name": "created_by_name",
    "label": "Name",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"$created_by_kind\"}, created_by_name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\",pod=~\"$created_by_name.*\"}) - sum(kube_pod_container_status_running{namespace=\"$namespace\",pod=~\"$created_by_name.*\"})"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\", pod=~\"$created_by_name.*\"})"
    }
   ]
  },
  {
   "title": "Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"$created_by_name.*\"})"
    }
   ]
  },
  {
   "title": "IO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_fs_io_current{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$created_by_name.*\"})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$created_by_name.*\"})"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$created_by_name.*\"})"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$created_by_name.*\"})"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\",container_name!=\"POD\"}[3m]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\",container_name!=\"POD\"}[3m]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\",container_name!=\"POD\"}[3m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\",image!=\"\",container_name!=\"POD\"}[3m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "rate(container_memory_rss{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\",image!=\"\",container_name!=\"POD\"}[3m])",
     "legendFormat": "RSS"
    },
    {
     "expr": "rate(container_memory_cache{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\",image!=\"\",container_name!=\"POD\"}[3m])",
     "legendFormat": "CACHE"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Network Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\"}[3m]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\"}[3m]))",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\"}[3m]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$namespace\",pod_name=~\"$created_by_name.*\"}[3m]))",
     "legendFormat": "OUT"
    }
   ]
  }
 ]
}