{
 "title": "Pod Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info,namespace)"
   },
   {
    "name": "created_by_kind",
    "label": "Kind",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"},created_by_kind)"
   },
   {
    "name": "created_by_name",
    "label": "Name",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"$created_by_kind\"}, created_by_name)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"$created_by_kind\",created_by_name=\"$created_by_name\"},pod)"
   },
   {
    "name": "pod_ip",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"$created_by_kind\",created_by_name=\"$created_by_name\", pod=\"$pod\"},pod_ip)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}) - sum(kube_pod_container_status_running{namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\", created_by_kind=\"$created_by_kind\", created_by_name=\"$created_by_name\"})"
    }
   ]
  },
  {
   "title": "Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "content": "<p aligen=center>\n  <font face=\"courier new\">\n    <b>Kind</b>: $created_by_kind<br />\n    <b>Name</b>: $created_by_name<br />\n    <b>Pod&nbsp;</b>: $pod<br />\n    <b>IP&nbsp;&nbsp;</b>: $pod_ip<br />\n  </font>\n</p>\n\n\n"
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"}) / 2"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"}) / 2"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}) / 2"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 4 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}) / 2"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{namespace=\"$namespace\",pod=\"$pod\",image!=\"\",container_name!=\"POD\"}[3m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{namespace=\"$namespace\",pod=\"$pod\",image!=\"\",container_name!=\"POD\"}[3m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",image!=\"\",container_name!=\"POD\"}[3m])",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_memory_usage_bytes{namespace=\"$namespace\",pod=\"$pod\",image!=\"\",container_name!=\"POD\"}[3m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(irate(container_memory_rss{namespace=\"$namespace\",pod=\"$pod\",image!=\"\",container_name!=\"POD\"}[3m]))",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(irate(container_memory_cache{namespace=\"$namespace\",pod=\"$pod\",image!=\"\",container_name!=\"POD\"}[3m]))",
     "legendFormat": "CACHE"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[3m])",
     "legendFormat": "IN"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[3m])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[3m])",
     "legendFormat": "IN"
    },
    {
     "expr": "irate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[3m])",
     "legendFormat": "OUT"
    }
   ]
  }
 ]
}