kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-es-search-data-1
  namespace: default
  annotations: 
    volume.beta.kubernetes.io/storage-class: data
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 10Gi
