# --------------------------------------------
# Created by Statemood, 2018.01.06
#            I.am.RuLin@gmail.com
#
# Project dockerfiles:
#    https://github.com/Statemood/dockerfiles
# --------------------------------------------

apiVersion: apps/v1beta2
kind: StatefulSet

metadata:
  name: es-search-client
  labels:
    component: elasticsearch
    role: client

spec:
  replicas: 1
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: es-search-client
  template:
    metadata:
      labels:
        app: es-search-client
        component: elasticsearch
        role: client
    spec:
      nodeSelector:
        zone: computational
      containers:
      - name: es-search-client
        image: statemood/elasticsearch:6.2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name:  "ES_JAVA_OPTS"
          value: "-Xms1g -Xmx1g"
        - name:  "ES_CLUSTER_NAME"
          value: "es-search"
        - name:  "ES_NODE_DATA"
          value: "false"
        - name:  "ES_NODE_MASTER"
          value: "false"
        - name:  "ES_HTTP_ENABLED"
          value: "true"
        - name:  "ES_UNICAST_HOSTS"
          value: "elasticsearch-discovery"
        resources:
          limits:
            cpu: "500m"
            memory: "1500Mi"
          requests:
            cpu: "200m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 20
