# --------------------------------------------
# Created by Statemood, 2018.01.06
#            I.am.RuLin@gmail.com
#
# Project dockerfiles:
#    https://github.com/Statemood/dockerfiles
# --------------------------------------------

apiVersion: apps/v1beta2
kind: StatefulSet

metadata:
  name: es-search-data
  namespace: default
  labels:
    component: elasticsearch
    role: data

spec:
  replicas: 1
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: es-search-data
  template:
    metadata:
      labels:
        app: es-search-data
        component: elasticsearch
        role: data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: key
                operator: In
                values:
                - value
      containers:
      - name: es-search-data
        image: statemood/elasticsearch:6.2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9300
          name: transport
        env:
        - name:  "JAVA_OPTS"
          value: "-Xms1g -Xmx1g -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
        - name:  "ES_JAVA_OPTS"
          value: "-Dbootstrap.memory_lock=false"
        - name:  "ES_CLUSTER_NAME"
          value: "es-search"
        - name:  "ES_NODE_DATA"
          value: "true"
        - name:  "ES_NODE_MASTER"
          value: "false"
        - name:  "ES_HTTP_ENABLED"
          value: "false"
        - name:  "ES_UNICAST_HOSTS"
          value: "elasticsearch-discovery"
        resources:
          limits:
            cpu: "1"
            memory: 1500Mi
          requests:
            cpu: "1"
            memory: 1500Mi
        livenessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 20
        volumeMounts:
        - name: data-es
          mountPath: /data
      volumes:
      - name: data-es
        hostPath:
          # If replicas = 2, create dir:
          #     es-search-data-0 and es-search-data-1 in /data/es/
          path: /data/es/es-search-data