apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    name: redis-sentinel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      name: redis-sentinel
  template:
    metadata:
      labels:
        name: redis-sentinel
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: redis-sentinel
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - 192.168.0.81
                - 192.168.0.82
                - 192.168.0.83
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-sentinel
        # Build your own image with Dockerfile at
        #     https://github.com/Statemood/dockerfiles/tree/master/Dockerfiles/redis/4.0.12
        image: statemood/redis:4.0.12
        imagePullPolicy: Always
        ports:
        - containerPort: 26379
          name: redis-sentinal
        env:
        - name: REDIS_MODE
          value: "sentinel"
        - name:  REDIS_MASTER_SVC_HOST
          value: "redis-master"
        - name:  REDIS_MASTER_SVC_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redisAuthPass
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 20