kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: data
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.50.55:6789,192.168.50.56:6789,192.168.50.57:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: data
  userId: kube
  userSecretName: ceph-secret-kube
